version: '3'

services:
  wechat2tg:
    image: finalpi/wechat2tg:latest
    container_name: wx2tg
    volumes:
      - ./config:/app/storage
      - ./save-files:/app/save-files # 保存文件夹挂载后表情不需要重新转换
    # use env file or you can jest set environment here
    env_file: "wechat2tg.env"
    # environment:
      # - BOT_TOKEN=
      # - PROXY_HOST=
      # - PROXY_PORT=
      # 代理类型:socks5,http,https
      # - PROXY_PROTOCOL=socks5
      # 用户名密码可选
      # - PROXY_USERNAME=
      # - PROXY_PASSWORD=
      # 发送大文件所需Telegram API配置(可选)
      #- API_ID=
      #- API_HASH=
    restart: unless-stopped
